# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21.5.0
      - run: npm install
      - run: npm link
      - name: Create Tests_Result directory if not exists
        run: mkdir -p __tests__/Tests_Result
      - name: Download Tests directory
        run: d-github https://github.com/ALeX400/d-github/tree/main/__tests__/Tests --output __tests__/Tests_Result
      - run: npm install -g mocha chai @types/chai
      - run: mocha __tests__/index.test.js

  publish-gpr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21.5.0
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NPM_ACCESS: ${{ secrets.NPM_ACCESS }}
      - run: echo "//https://registry.npmjs.org/:_authToken=${{secrets.NPM_ACCESS}}" > ~/.npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS}}
